select * from customer limit 10;

--Business questions 
--1 What is the total revenue generated by male vs female customers?;
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

--2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount >=(select AVG(purchase_amount) from customer)

--3. which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4. Compare the average purchase amount between standard and Express shipping?
select shipping_type, ROUND(AVG(purchase_amount),2) as "Average Revenue"
from customer
where shipping_type in ('Express', 'Standard')
group by shipping_type;

--5. Do subscribed customers spend more? compare average speed and total revenue between subscribers and non-subscribers?
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as average_spend, 
SUM(purchase_amount) as total_revenue
from customer
group by subscription_status
order by total_revenue desc;

--6. Which 5 products have the highest percentage of purchases with discounts applies?
select item_purchased,
ROUND(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7. Segment customers into New, Returning, and loyal based on their total number of previous purchases
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases =1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer
)
 select customer_segment, 
 count(*) as "Number of customers"
 from customer_type
 group by customer_segment;

 --Q8. What are the top 3 most purchased products within each category?
with item_count as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, item_purchased, total_orders
from item_count
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as "repeat buyers" 
from customer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as "total revenue"
from customer
group by age_group
order by "total revenue" desc;

 

